config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # You can have the root of your site routed with "root"
  root to: 'quizzes#index'

  resources :quizzes do
    collection do
      get :quiz_result
    end
    resources :questions do
      resources :answers
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  belongs_to :quiz
  belongs_to :question
  belongs_to :user
  validates_presence_of :response
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers
  enum question_type: %i[text textarea].freeze
  validates_presence_of :title, :question_type
  accepts_nested_attributes_for :answers
end

app/models/quiz.rb
# frozen_string_literal: true

class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :answers
  validates_presence_of :name
  accepts_nested_attributes_for :questions
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quizzes
  has_many :answers
  enum role: %i[admin user].freeze
  validates_presence_of :name, :role
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
# controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: %i[new create]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id
    @answer.quiz_id = params[:quiz_id]
    if @answer.save
      redirect_to quiz_questions_path(quiz_id: params[:quiz_id]), notice: 'answer created'
    else
      redirect_to root_path, notice: 'answer has not been created'
    end
  end

  private

  def set_question
    @question = Question.find_by_id(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:response, :question_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  def authenticate_admin!
    redirect_to root_path, notice: 'Not authorize' unless current_user.admin?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_quiz, only: [:index, :new, :create]
  before_action :set_question, only: [:show, :destroy, :update]

  def index
    @questions = @quiz.questions
  end

  def new
    @question = @quiz.questions.build
  end

  def create
    @question = @quiz.questions.build(question_params)
    if @question.save
      redirect_to quizzes_path, notice: 'Question has been created'
    else
      redirect_to root_path, notice: 'Question has not been created'
    end
  end

  def show; end

  def destroy
    if @question.destroy
      redirect_to quizzes_path, notice: 'Question has been removed'
    else
      redirect_to root_path, notice: 'Question has not been removed'
    end
  end

  private

  def set_quiz
    @quiz = Quiz.find_by_id(params[:quiz_id])
  end

  def set_question
    @question = Question.find_by_id(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :question_type)
  end
end

app/controllers/quizzes_controller.rb
# frozen_string_literal: true

class QuizzesController < ApplicationController
  before_action :authenticate_admin!, except: [:index]

  def index
    if current_user.admin?
      @quizzes = current_user.quizzes
    else
      @quizzes = Quiz.all
    end
  end

  def new
    @quiz = current_user.quizzes.new
    @question = @quiz.questions.new
  end

  def create
    @quiz = current_user.quizzes.create(quiz_params)
    if @quiz.save
      redirect_to quizzes_path, notice: 'Quiz has been created'
    else
      redirect_to root_path, notice: 'Quiz has not been created'
    end
  end

  def destroy
    quiz = Quiz.find_by_id(params[:id])
    if quiz.destroy
      redirect_to quizzes_path, notice: 'Quiz has been deleted'
    else
      redirect_to root_path, notice: 'Quiz has not been deleted'
    end
  end

  def quiz_result
    @quiz = Quiz.find_by_id(params[:quiz_id])

    @results = @quiz.questions.map do |question|
                  [question.title, question.answers.map(&:response).join(',')]
               end
  end

  private

  def quiz_params
    params.require(:quiz).permit(:name, questions_attributes: [:title, :question_type])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/quizzes_helper.rb
# frozen_string_literal: true

module QuizzesHelper
end

app/views/answers/new.html.erb
<div class="new_quiz">
<div class="container">
  <h3><Strong>Answer Details</Strong></h3>
  <%= form_for @answer, :url=> quiz_question_answers_path,  method: :post do |f| %>
    <% if @answer.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="information-list">
        <div class="field">
          <%= f.label :Response, class: "form-group" %>
          <%= f.text_field :response, :required => true, class: "form-control" %>
        </div>
      </div>  
    </div>
<br>
<br>
    <div class="row">
      <div class="col-md-6">
        <div class="actions">
          <%= f.submit "Save", class:"btn btn-primary" %>
        </div>
      </div>

      <div class="col-md-6">
        <%= link_to "Back", :back, class:"btn btn-link" %>
      </div>
    <br>
    </div>
   <% end %>
</div>
</div>

app/views/home/index.html.erb
<div class="home_index">
</div> 

app/views/layouts/_header.html.erb
<nav class="navbar-inverse">
  <!-- <div class="container"> -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to 'Quiz Builder', root_path, :class => 'navbar-brand' %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <div class ="link">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to('Home',root_path) %></li>
            <li><%= link_to('Profile', edit_user_registration_path) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to('Add Quiz', new_quiz_path) if current_user.admin? %></li>
            <li><%= link_to('Quiz List', quizzes_path) %></li>
          <% else %>
            <li><%= link_to('Sign in', new_user_session_path) %></li>
            <li><%= link_to('Sign up', new_user_registration_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <!-- </div> -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizBuilderApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %> 
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/index.html.erb
<div class=question_index>
  <h2>Question List</h2>
  <table class="table table-bordered">
    <thread>
      <tr>
        <th>Title</th>
        <th>QuestionType</th>
        <% if current_user.admin? %>
          <th>Delete</th>
        <% else %>
          <th>Add Answer</th>
        <% end %>
      </tr>
    </thread>
    <tbody>
      <% if @questions.blank? %>
        <tr>
          <td colspan="4" align="center"> No Record Found </td>
        </tr>
      <% else %>
        <% @questions.each do |q| %>
          <tr>
            <td><%= q.title %></td>
            <td><%= q.question_type %></td>
            <% if current_user.admin? %>
              <td> <%= link_to 'Destroy', quiz_question_path(id: q.id), method: :DELETE %></td>
            <% else %>
              <% if q.answers&.where(user_id: current_user.id).present? %> 
                <td><%= q.answers.where(user_id: current_user.id).first.response %></td>
              <% else %>
                <td><%= link_to 'add', new_quiz_question_answer_path(quiz_id: q.quiz.id, question_id: q.id) %></td>
              <% end %>         
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
      <%= link_to "Back", :back, class:"btn btn-primary" %>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="new_quiz">
  <div class="container">
    <h3><Strong>Question Details</Strong></h3>
    <%= form_for @question, :url=> quiz_questions_path, method: :post do |f| %>
      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
          <ul>
            <% @question.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <h3><Strong>Question Details</Strong></h3>
          <div class="information-list">
            <div class="field">
              <%= f.label :Title, class: "form-group" %>
              <%= f.text_field :title, :required => true, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :QuestionType, class: "form-group" %>
              <%= f.select :question_type, options_for_select(Question.question_types.map {|key, value| [key.titleize, Question.question_types.key(value)]}, @question.question_type ), :required => true, class: "form-control" %>
            </div>
          </div>
          <div class="actions">
            <%= f.submit "Save", class:"btn btn-primary" %>
          </div>
          <div class="actions">
            <%= link_to "Back", :back, class:"btn btn-link" %>
          </div>
        </div> 
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/_question_fields.html.erb
<div class = "nested-fields">
  <div class="field">
    <%= f.label :title, class: "form-group" %>
    <%= f.text_field :title, :required => true, class: "form-control" %>
  </div><br/>

  <div class="field">
    <%= f.label :question_type, class: "form-group" %>
    <%= f.select :question_type, options_for_select(Question.question_types.map {|key, value| [key.titleize, Question.question_types.key(value)]}, @question.question_type ), :required => true, class: "form-control" %>
  </div>
    <%= link_to_remove_association "remove questions", f %>
</div>

app/views/quizzes/index.html.erb
<div class=quiz_index>
  <div class="row">
    <div class="col-md-9">
      <h2>Quiz List</h2>
    </div>
    <div class="col-md-3 text-right">
      <%= link_to 'Add Quiz', new_quiz_path, class: 'btn btn-primary' if current_user.admin? %>
    </div>
  </div>
</div>
  <table class="table table-bordered">
    <thread>
      <tr>
        <th>QuizName</th>
        <th>View Question</th>
        <% if current_user.admin? %>
          <th>Add Question</th>
          <th>delete</th>
          <th>Quiz Result</th>
        <% end %>
      </tr>
    </thread>
    <tbody>
      <% if @quizzes.blank? %>
      <tr>
        <td colspan="4" align="center"> No Record Found </td>
      </tr>
      <% else %>
        <% @quizzes.each do |q| %>
          <tr>
            <td><%= q.name %></td>
            <td><%= link_to 'view', quiz_questions_path(quiz_id: q.id) %></td>
            <% if current_user.admin? %>
              <td><%= link_to 'add', new_quiz_question_path(quiz_id: q.id) %></td>
              <td><%= link_to 'destroy', quiz_path(id: q.id), method: :DELETE %></td>
              <td><%= link_to 'Quiz Result', quiz_result_quizzes_path(quiz_id: q.id) %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <%= link_to "Back", :back, class:"btn btn-primary" %>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/quizzes/new.html.erb
<div class="new_quiz">
  <div class="container">
    <%= form_for @quiz, url: quizzes_path, method: :post do |f| %>
      <% if @quiz.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>
          <ul>
            <% @quiz.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <h3><Strong>Quiz Details</Strong></h3>
          <div class="information-list">
            <div class="field">
              <%= f.label :name, class: "form-group" %>
              <%= f.text_field :name, :required => true, class: "form-control" %>
            </div>
          </div>  
          <h3><strong>Question List</strong></h3>
          <div class="information-list">
            <%= f.fields_for :questions do |question| %>
              <%= render 'question_fields', f: question %>
              <br>
              <div class="link">
                <h1></h1><%= link_to_add_association('Add More Question', f, :questions) %>
              </div>
            <% end %>
          </div>
          <br>
          <div class="actions">
            <%= f.submit "Save", class:"btn btn-primary" %>
          </div>
            <%= link_to "Back", :back, class:"btn btn-link" %>
          <br>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/quiz_result.html.erb
<div class=quiz_index>
  <h2>Quiz Result</h2>
  <table class="table table-bordered">
    <thread>
      <tr>
        <th>Question</th>
        <th>Answers</th>
      </tr>
    </thread>
    <tbody>
      <% if @results.blank? %>
        <tr>
          <td colspan="4" align="center"> No Record Found </td>
        </tr>
      <% else %>
        <% @results.each do |result| %>
          <tr>
            <td><%= result.first %></td>
            <td><%= result.last.split(",").join("<br/>").html_safe %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      <%= link_to "Back", :back, class:"btn btn-primary" %>
    </div>
    <div class="col-md-3">
      <li><%= link_to 'Add Quiz', new_quiz_path, :class => 'btn btn-primary' if current_user.admin? %></li>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>